package com.nimbusbill.customer.service;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @Transactional public class BillingService {
 private final BillingAccountRepository accounts; private final BillingPeriodRepository periods; private final BillingRunRepository runs; private final BillingRunItemRepository items; private final BillingChargeRepository charges; private final CustomerRepository customers;
 public BillingService(BillingAccountRepository a,BillingPeriodRepository p,BillingRunRepository r,BillingRunItemRepository i,BillingChargeRepository c,CustomerRepository customers){accounts=a;periods=p;runs=r;items=i;charges=c;this.customers=customers;}
 public BillingAccountResponse createAccount(BillingAccountRequest request){Customer customer=customers.findById(request.customerId()).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+request.customerId()));if(accounts.existsByCustomerIdAndAccountCodeIgnoreCase(customer.getId(),request.accountCode()))throw new ConflictException("Billing account code already exists: "+request.accountCode());BillingAccount a=new BillingAccount();a.setCustomer(customer);a.setAccountCode(request.accountCode().trim().toUpperCase());a.setAccountName(request.accountName().trim());a.setCurrency(request.currency().toUpperCase());a.setBillingCycle(request.billingCycle());a.setPaymentTermsDays(request.paymentTermsDays());return account(accounts.save(a));}
 @Transactional(readOnly=true) public List<BillingAccountResponse> listAccounts(UUID customerId){return accounts.findByCustomerIdOrderByAccountName(customerId).stream().map(this::account).toList();}
 public BillingPeriodResponse createPeriod(BillingPeriodRequest request){if(request.periodEnd().isBefore(request.periodStart()))throw new IllegalArgumentException("periodEnd cannot precede periodStart");BillingAccount account=accounts.findById(request.billingAccountId()).orElseThrow(()->new ResourceNotFoundException("Billing account not found: "+request.billingAccountId()));if(!"ACTIVE".equals(account.getStatus()))throw new ConflictException("Billing account is not active");BillingPeriod p=new BillingPeriod();p.setBillingAccount(account);p.setPeriodStart(request.periodStart());p.setPeriodEnd(request.periodEnd());return period(periods.save(p));}
 @Transactional(readOnly=true) public List<BillingPeriodResponse> listPeriods(UUID accountId){return periods.findByBillingAccountIdOrderByPeriodStartDesc(accountId).stream().map(this::period).toList();}
 public BillingRunResponse preview(UUID periodId){BillingPeriod p=findPeriod(periodId);if("CLOSED".equals(p.getStatus()))throw new ConflictException("Billing period is closed");List<TransactionCharge> pending=pending(p);BillingRun run=new BillingRun();run.setBillingPeriod(p);run.setStatus("PREVIEWED");totals(run,pending);return response(runs.save(run));}
 public BillingRunResponse execute(UUID runId){BillingRun run=runs.findById(runId).orElseThrow(()->new ResourceNotFoundException("Billing run not found: "+runId));if(!"PREVIEWED".equals(run.getStatus()))throw new ConflictException("Only previewed billing runs can be executed");BillingPeriod period=run.getBillingPeriod();run.setStatus("PROCESSING");period.setStatus("PROCESSING");List<TransactionCharge> pending=pending(period);for(TransactionCharge charge:pending){BillingRunItem item=new BillingRunItem();item.setBillingRun(run);item.setCharge(charge);item.setTransactionId(charge.getTransaction().getId());item.setProductCode(charge.getTransaction().getProductCode());item.setBaseFee(charge.getBaseFee());item.setTaxAmount(charge.getTaxAmount());item.setTotalAmount(charge.getChargeAmount());item.setCurrency(charge.getCurrency());items.save(item);charge.setStatus("BILLED");charges.save(charge);}totals(run,pending);run.setStatus("COMPLETED");run.setCompletedAt(Instant.now());period.setStatus("CLOSED");period.setClosedAt(Instant.now());periods.save(period);return response(runs.save(run));}
 @Transactional(readOnly=true) public List<BillingRunResponse> listRuns(UUID customerId){return runs.findByBillingPeriodBillingAccountCustomerIdOrderByStartedAtDesc(customerId).stream().map(this::response).toList();}
 private List<TransactionCharge> pending(BillingPeriod p){Instant start=p.getPeriodStart().atStartOfDay(ZoneOffset.UTC).toInstant();Instant end=p.getPeriodEnd().plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant();BillingAccount a=p.getBillingAccount();return charges.lockPending(a.getCustomer().getId(),a.getCurrency(),start,end);}
 private void totals(BillingRun run,List<TransactionCharge> cs){run.setChargeCount(cs.size());run.setSubtotal(cs.stream().map(TransactionCharge::getBaseFee).reduce(BigDecimal.ZERO,BigDecimal::add));run.setTaxTotal(cs.stream().map(TransactionCharge::getTaxAmount).reduce(BigDecimal.ZERO,BigDecimal::add));run.setGrandTotal(cs.stream().map(TransactionCharge::getChargeAmount).reduce(BigDecimal.ZERO,BigDecimal::add));}
 private BillingPeriod findPeriod(UUID id){return periods.findById(id).orElseThrow(()->new ResourceNotFoundException("Billing period not found: "+id));}
 private BillingAccountResponse account(BillingAccount a){return new BillingAccountResponse(a.getId(),a.getCustomer().getId(),a.getAccountCode(),a.getAccountName(),a.getCurrency(),a.getBillingCycle(),a.getPaymentTermsDays(),a.getStatus(),a.getCreatedAt());}
 private BillingPeriodResponse period(BillingPeriod p){return new BillingPeriodResponse(p.getId(),p.getBillingAccount().getId(),p.getPeriodStart(),p.getPeriodEnd(),p.getStatus(),p.getClosedAt());}
 private BillingRunResponse response(BillingRun r){return new BillingRunResponse(r.getId(),r.getBillingPeriod().getId(),r.getBillingPeriod().getBillingAccount().getId(),r.getStatus(),r.getChargeCount(),r.getSubtotal(),r.getTaxTotal(),r.getGrandTotal(),r.getStartedAt(),r.getCompletedAt(),r.getFailureReason());}
}
