package com.nimbusbill.customer.service; import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional public class CustomerConfigurationService{private final CustomerRepository customers;private final PaymentProductRepository products;private final CustomerProductRepository customerProducts;private final PricingPlanRepository plans;private final CustomerPricingAssignmentRepository assignments;private final PricingOverrideRepository overrides;public CustomerConfigurationService(CustomerRepository c,PaymentProductRepository p,CustomerProductRepository cp,PricingPlanRepository plans,CustomerPricingAssignmentRepository a,PricingOverrideRepository overrides){customers=c;products=p;customerProducts=cp;this.plans=plans;assignments=a;this.overrides=overrides;}
 @Transactional(readOnly=true) public List<CustomerProductResponse> products(UUID customerId){customer(customerId);return customerProducts.findByCustomerIdOrderByProductProductName(customerId).stream().map(this::productResponse).toList();}
 public List<CustomerProductResponse> setProducts(UUID customerId,List<CustomerProductRequest> requests){Customer c=customer(customerId);for(CustomerProductRequest r:requests){if(r.expiryDate()!=null&&r.expiryDate().isBefore(r.activationDate()))throw new IllegalArgumentException("expiryDate cannot precede activationDate");if(r.transactionLimit()!=null&&r.dailyLimit()!=null&&r.transactionLimit().compareTo(r.dailyLimit())>0)throw new IllegalArgumentException("transactionLimit cannot exceed dailyLimit");PaymentProduct p=products.findById(r.productId()).orElseThrow(()->new ResourceNotFoundException("Product not found: "+r.productId()));CustomerProduct cp=customerProducts.findByCustomerIdAndProductId(customerId,r.productId()).orElseGet(CustomerProduct::new);cp.setCustomer(c);cp.setProduct(p);cp.setEnabled(r.enabled());cp.setActivationDate(r.activationDate());cp.setExpiryDate(r.expiryDate());cp.setBillingAccountId(r.billingAccountId());cp.setTransactionLimit(r.transactionLimit());cp.setDailyLimit(r.dailyLimit());customerProducts.save(cp);}return products(customerId);}
 @Transactional(readOnly=true) public List<CustomerPricingResponse> pricing(UUID customerId){customer(customerId);return assignments.findByCustomerIdOrderByEffectiveFromDesc(customerId).stream().map(this::pricingResponse).toList();}
 public CustomerPricingResponse assign(UUID customerId,CustomerPricingRequest r){Customer c=customer(customerId);if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");PricingPlan p=plans.findById(r.planId()).orElseThrow(()->new ResourceNotFoundException("Pricing plan not found: "+r.planId()));assignments.findByCustomerIdOrderByEffectiveFromDesc(customerId).stream().filter(CustomerPricingAssignment::isActive).forEach(a->{a.setActive(false);assignments.save(a);});CustomerPricingAssignment a=new CustomerPricingAssignment();a.setCustomer(c);a.setPlan(p);a.setEffectiveFrom(r.effectiveFrom());a.setEffectiveTo(r.effectiveTo());a.setActive(true);return pricingResponse(assignments.save(a));}
 @Transactional(readOnly=true) public List<PricingOverrideResponse> overrides(UUID customerId){customer(customerId);return overrides.findByCustomerIdOrderByEffectiveFromDesc(customerId).stream().map(this::overrideResponse).toList();}
 public PricingOverrideResponse createOverride(UUID customerId,PricingOverrideRequest r,String actor){Customer c=customer(customerId);PaymentProduct p=products.findById(r.productId()).orElseThrow(()->new ResourceNotFoundException("Product not found: "+r.productId()));validateOverride(r);if(overrides.overlaps(customerId,p.getId(),r.effectiveFrom(),r.effectiveTo(),UUID.randomUUID()))throw new ConflictException("An active pricing override already overlaps this product and date range");PricingOverride o=new PricingOverride();o.setCustomer(c);o.setProduct(p);apply(o,r);o.setCreatedBy(actor);return overrideResponse(overrides.save(o));}
 public PricingOverrideResponse updateOverride(UUID customerId,UUID id,PricingOverrideRequest r){PricingOverride o=findOverride(customerId,id);PaymentProduct p=products.findById(r.productId()).orElseThrow(()->new ResourceNotFoundException("Product not found: "+r.productId()));validateOverride(r);if(overrides.overlaps(customerId,p.getId(),r.effectiveFrom(),r.effectiveTo(),id))throw new ConflictException("An active pricing override already overlaps this product and date range");o.setProduct(p);apply(o,r);return overrideResponse(overrides.save(o));}
 public void deactivateOverride(UUID customerId,UUID id){PricingOverride o=findOverride(customerId,id);o.setActive(false);overrides.save(o);}
 private PricingOverride findOverride(UUID customerId,UUID id){PricingOverride o=overrides.findById(id).orElseThrow(()->new ResourceNotFoundException("Pricing override not found: "+id));if(!o.getCustomer().getId().equals(customerId))throw new ResourceNotFoundException("Pricing override not found for customer");return o;}
 private void apply(PricingOverride o,PricingOverrideRequest r){o.setChargeType(r.chargeType());o.setFixedFee(r.fixedFee());o.setPercentageRate(r.percentageRate());o.setMinimumFee(r.minimumFee());o.setMaximumFee(r.maximumFee());o.setTaxRate(r.taxRate());o.setEffectiveFrom(r.effectiveFrom());o.setEffectiveTo(r.effectiveTo());o.setReason(r.reason()==null||r.reason().isBlank()?null:r.reason().trim());o.setActive(true);}
 private void validateOverride(PricingOverrideRequest r){if(r.chargeType()==PricingUnit.SLAB)throw new IllegalArgumentException("SLAB is not supported for customer overrides");if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");if(r.minimumFee()!=null&&r.maximumFee()!=null&&r.minimumFee().compareTo(r.maximumFee())>0)throw new IllegalArgumentException("minimumFee cannot exceed maximumFee");if((r.chargeType()==PricingUnit.FIXED||r.chargeType()==PricingUnit.HYBRID)&&r.fixedFee()==null)throw new IllegalArgumentException("fixedFee is required");if((r.chargeType()==PricingUnit.PERCENTAGE||r.chargeType()==PricingUnit.HYBRID)&&r.percentageRate()==null)throw new IllegalArgumentException("percentageRate is required");}
 private PricingOverrideResponse overrideResponse(PricingOverride o){return new PricingOverrideResponse(o.getId(),o.getCustomer().getId(),o.getProduct().getId(),o.getProduct().getProductCode(),o.getProduct().getProductName(),o.getChargeType(),o.getFixedFee(),o.getPercentageRate(),o.getMinimumFee(),o.getMaximumFee(),o.getTaxRate(),o.getEffectiveFrom(),o.getEffectiveTo(),o.isActive(),o.getReason(),o.getCreatedBy(),o.getCreatedAt(),o.getUpdatedAt());}
 private Customer customer(UUID id){return customers.findById(id).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+id));}private CustomerProductResponse productResponse(CustomerProduct x){return new CustomerProductResponse(x.getId(),x.getProduct().getId(),x.getProduct().getProductCode(),x.getProduct().getProductName(),x.isEnabled(),x.getActivationDate(),x.getExpiryDate(),x.getBillingAccountId(),x.getTransactionLimit(),x.getDailyLimit());}private CustomerPricingResponse pricingResponse(CustomerPricingAssignment x){return new CustomerPricingResponse(x.getId(),x.getPlan().getId(),x.getPlan().getPlanCode(),x.getPlan().getPlanName(),x.getEffectiveFrom(),x.getEffectiveTo(),x.isActive());}}
