package com.nimbusbill.customer.service;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service @Transactional public class InvoiceLifecycleService {
 private final CustomerTaxProfileRepository taxes; private final CustomerRepository customers; private final InvoiceRepository invoices; private final InvoiceAdjustmentRepository adjustments; private final InvoiceDeliveryRepository deliveries; private final InvoiceStatusHistoryRepository history;
 public InvoiceLifecycleService(CustomerTaxProfileRepository t,CustomerRepository c,InvoiceRepository i,InvoiceAdjustmentRepository a,InvoiceDeliveryRepository d,InvoiceStatusHistoryRepository h){taxes=t;customers=c;invoices=i;adjustments=a;deliveries=d;history=h;}
 public TaxProfileResponse saveTax(UUID customerId,TaxProfileRequest r){Customer customer=customers.findById(customerId).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+customerId));CustomerTaxProfile p=taxes.findByCustomerId(customerId).orElseGet(CustomerTaxProfile::new);p.setCustomer(customer);p.setTaxIdentifier(r.taxIdentifier());p.setTaxCountry(r.taxCountry().toUpperCase());p.setTaxRegion(r.taxRegion());p.setPlaceOfSupply(r.placeOfSupply());p.setDefaultTaxRate(r.defaultTaxRate());p.setTaxExempt(r.taxExempt());p.setEffectiveFrom(r.effectiveFrom());return tax(taxes.save(p));}
 @Transactional(readOnly=true) public TaxProfileResponse getTax(UUID customerId){return tax(taxes.findByCustomerId(customerId).orElseThrow(()->new ResourceNotFoundException("Tax profile not found for customer: "+customerId)));}
 public void adjust(UUID invoiceId,InvoiceAdjustmentRequest r){Invoice i=find(invoiceId);if(!List.of("DRAFT","REJECTED").contains(i.getStatus()))throw new ConflictException("Adjustments require a draft or rejected invoice");InvoiceAdjustment a=new InvoiceAdjustment();a.setInvoice(i);a.setAdjustmentType(r.adjustmentType());a.setAmount(r.amount());a.setReason(r.reason());a.setCreatedBy("billing-manager");adjustments.save(a);recalculate(i);}
 public void reject(UUID id,String comment){change(id,"SUBMITTED","REJECTED",comment);}
 public void reopen(UUID id,String comment){change(id,"REJECTED","DRAFT",comment);}
 public void dispute(UUID id,String comment){change(id,"ISSUED","DISPUTED",comment);}
 public void markPaid(UUID id,String comment){Invoice i=find(id);if(!List.of("ISSUED","OVERDUE","DISPUTED").contains(i.getStatus()))throw new ConflictException("Only issued, overdue or disputed invoices can be paid");change(id,i.getStatus(),"PAID",comment);}
 public InvoiceDeliveryResponse deliver(UUID id,InvoiceDeliveryRequest r){Invoice i=find(id);if(!"ISSUED".equals(i.getStatus()))throw new ConflictException("Only issued invoices can be delivered");InvoiceDelivery d=new InvoiceDelivery();d.setInvoice(i);d.setChannel(r.channel());d.setDestination(r.destination());d.setStatus("DELIVERED");d.setDeliveredAt(Instant.now());return delivery(deliveries.save(d));}
 @Transactional(readOnly=true) public List<InvoiceDeliveryResponse> deliveries(UUID id){find(id);return deliveries.findByInvoiceIdOrderByCreatedAtDesc(id).stream().map(this::delivery).toList();}
 private void recalculate(Invoice i){BigDecimal total=adjustments.findByInvoiceId(i.getId()).stream().map(a->"CREDIT".equals(a.getAdjustmentType())?a.getAmount().negate():a.getAmount()).reduce(BigDecimal.ZERO,BigDecimal::add);i.setAdjustmentTotal(total);i.setGrandTotal(i.getSubtotal().add(i.getTaxTotal()).add(total));invoices.save(i);}
 private void change(UUID id,String expected,String target,String comment){Invoice i=find(id);if(!expected.equals(i.getStatus()))throw new ConflictException("Invoice must be "+expected+" before "+target);String old=i.getStatus();i.setStatus(target);invoices.save(i);InvoiceStatusHistory h=new InvoiceStatusHistory();h.setInvoice(i);h.setFromStatus(old);h.setToStatus(target);h.setActor("invoice-service");h.setComment(comment);history.save(h);}
 private Invoice find(UUID id){return invoices.findById(id).orElseThrow(()->new ResourceNotFoundException("Invoice not found: "+id));}
 private TaxProfileResponse tax(CustomerTaxProfile p){return new TaxProfileResponse(p.getId(),p.getCustomer().getId(),p.getTaxIdentifier(),p.getTaxCountry(),p.getTaxRegion(),p.getPlaceOfSupply(),p.getDefaultTaxRate(),p.isTaxExempt(),p.getEffectiveFrom());}
 private InvoiceDeliveryResponse delivery(InvoiceDelivery d){return new InvoiceDeliveryResponse(d.getId(),d.getChannel(),d.getDestination(),d.getStatus(),d.getAttemptCount(),d.getLastError(),d.getCreatedAt(),d.getDeliveredAt());}
}
