package com.nimbusbill.customer.service;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*; import java.util.*;
@Service @Transactional public class InvoiceService {
 private final InvoiceRepository invoices; private final InvoiceLineItemRepository lines; private final InvoiceStatusHistoryRepository history; private final BillingRunRepository runs; private final BillingRunItemRepository runItems;
 public InvoiceService(InvoiceRepository i,InvoiceLineItemRepository l,InvoiceStatusHistoryRepository h,BillingRunRepository r,BillingRunItemRepository ri){invoices=i;lines=l;history=h;runs=r;runItems=ri;}
 public InvoiceResponse generate(UUID runId){var existing=invoices.findByBillingRunId(runId);if(existing.isPresent())return response(existing.get());BillingRun run=runs.findById(runId).orElseThrow(()->new ResourceNotFoundException("Billing run not found: "+runId));if(!"COMPLETED".equals(run.getStatus()))throw new ConflictException("Invoice requires a completed billing run");BillingAccount account=run.getBillingPeriod().getBillingAccount();LocalDate date=LocalDate.now();Invoice invoice=new Invoice();invoice.setBillingRun(run);invoice.setCustomer(account.getCustomer());invoice.setBillingAccount(account);invoice.setInvoiceNumber("INV-"+date.getYear()+"-"+String.format("%06d",invoices.nextNumber()));invoice.setInvoiceDate(date);invoice.setDueDate(date.plusDays(account.getPaymentTermsDays()));invoice.setCurrency(account.getCurrency());invoice.setSubtotal(run.getSubtotal());invoice.setTaxTotal(run.getTaxTotal());invoice.setAdjustmentTotal(BigDecimal.ZERO);invoice.setGrandTotal(run.getGrandTotal());invoice=invoices.save(invoice);for(BillingRunItem source:runItems.findByBillingRunIdOrderByProductCode(runId)){InvoiceLineItem line=new InvoiceLineItem();line.setInvoice(invoice);line.setBillingRunItem(source);line.setTransactionId(source.getTransactionId());line.setProductCode(source.getProductCode());line.setDescription(source.getProductCode()+" transaction charge");line.setBaseAmount(source.getBaseFee());line.setTaxAmount(source.getTaxAmount());line.setTotalAmount(source.getTotalAmount());line.setCurrency(source.getCurrency());lines.save(line);}record(invoice,null,"DRAFT","Invoice generated");return response(invoice);}
 public InvoiceResponse submit(UUID id,String comment){return transition(id,"DRAFT","SUBMITTED",comment);}
 public InvoiceResponse approve(UUID id,String comment){return transition(id,"SUBMITTED","APPROVED",comment);}
 public InvoiceResponse issue(UUID id,String comment){return transition(id,"APPROVED","ISSUED",comment);}
 public InvoiceResponse cancel(UUID id,String comment){Invoice invoice=find(id);if("ISSUED".equals(invoice.getStatus()))throw new ConflictException("Issued invoices cannot be cancelled in this phase");return transition(id,invoice.getStatus(),"CANCELLED",comment);}
 @Transactional(readOnly=true) public List<InvoiceResponse> list(UUID customerId){return invoices.findByCustomerIdOrderByCreatedAtDesc(customerId).stream().map(this::response).toList();}
 @Transactional(readOnly=true) public InvoiceResponse get(UUID id){return response(find(id));}
 private InvoiceResponse transition(UUID id,String expected,String target,String comment){Invoice invoice=find(id);if(!expected.equals(invoice.getStatus()))throw new ConflictException("Invoice must be "+expected+" before "+target);String old=invoice.getStatus();invoice.setStatus(target);Instant now=Instant.now();if("SUBMITTED".equals(target))invoice.setSubmittedAt(now);if("APPROVED".equals(target))invoice.setApprovedAt(now);if("ISSUED".equals(target))invoice.setIssuedAt(now);invoices.save(invoice);record(invoice,old,target,comment);return response(invoice);}
 private Invoice find(UUID id){return invoices.findById(id).orElseThrow(()->new ResourceNotFoundException("Invoice not found: "+id));}
 private void record(Invoice invoice,String from,String to,String comment){InvoiceStatusHistory h=new InvoiceStatusHistory();h.setInvoice(invoice);h.setFromStatus(from);h.setToStatus(to);h.setActor("invoice-service");h.setComment(comment);history.save(h);}
 private InvoiceResponse response(Invoice i){var detail=lines.findByInvoiceIdOrderByProductCode(i.getId()).stream().map(l->new InvoiceResponse.Line(l.getId(),l.getTransactionId(),l.getProductCode(),l.getDescription(),l.getBaseAmount(),l.getTaxAmount(),l.getTotalAmount(),l.getCurrency())).toList();return new InvoiceResponse(i.getId(),i.getBillingRun().getId(),i.getCustomer().getId(),i.getBillingAccount().getId(),i.getInvoiceNumber(),i.getStatus(),i.getInvoiceDate(),i.getDueDate(),i.getCurrency(),i.getSubtotal(),i.getTaxTotal(),i.getAdjustmentTotal(),i.getGrandTotal(),i.getCreatedAt(),i.getSubmittedAt(),i.getApprovedAt(),i.getIssuedAt(),detail);}
}
