package com.nimbusbill.customer.service;
import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.repository.InvoiceDeliveryRepository; import org.springframework.beans.factory.ObjectProvider; import org.springframework.beans.factory.annotation.Value; import org.springframework.mail.SimpleMailMessage; import org.springframework.mail.javamail.JavaMailSender; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.net.URI; import java.net.http.*; import java.time.Instant; import java.util.UUID;
@Service public class InvoiceDeliveryProcessor {
 private final InvoiceDeliveryRepository deliveries; private final ObjectProvider<JavaMailSender> mail; private final HttpClient http=HttpClient.newHttpClient(); @Value("${app.mail.from:billing@nimbusbill.local}") private String from;
 public InvoiceDeliveryProcessor(InvoiceDeliveryRepository d,ObjectProvider<JavaMailSender> m){deliveries=d;mail=m;}
 @Transactional public void process(UUID id){InvoiceDelivery d=deliveries.findById(id).orElseThrow();try{if("EMAIL".equals(d.getChannel()))email(d);else if("WEBHOOK".equals(d.getChannel()))webhook(d);d.setStatus("DELIVERED");d.setLastError(null);d.setDeliveredAt(Instant.now());}catch(Exception e){d.setStatus("FAILED");d.setLastError(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage());}deliveries.save(d);}
 @Scheduled(fixedDelayString="${app.invoice.delivery-retry-ms:60000}") public void retry(){for(InvoiceDelivery d:deliveries.findByStatusAndAttemptCountLessThan("FAILED",3)){d.setAttemptCount(d.getAttemptCount()+1);deliveries.save(d);process(d.getId());}}
 private void email(InvoiceDelivery d){JavaMailSender sender=mail.getIfAvailable();if(sender==null)throw new IllegalStateException("SMTP is not configured");SimpleMailMessage m=new SimpleMailMessage();m.setFrom(from);m.setTo(d.getDestination());m.setSubject("NimbusBill invoice "+d.getInvoice().getInvoiceNumber());m.setText("Invoice "+d.getInvoice().getInvoiceNumber()+" for "+d.getInvoice().getCurrency()+" "+d.getInvoice().getGrandTotal()+" is available in NimbusBill.");sender.send(m);}
 private void webhook(InvoiceDelivery d)throws Exception{Invoice i=d.getInvoice();String body="{\"invoiceId\":\""+i.getId()+"\",\"invoiceNumber\":\""+i.getInvoiceNumber()+"\",\"status\":\""+i.getStatus()+"\",\"total\":"+i.getGrandTotal()+"}";HttpRequest request=HttpRequest.newBuilder(URI.create(d.getDestination())).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<Void> response=http.send(request,HttpResponse.BodyHandlers.discarding());if(response.statusCode()<200||response.statusCode()>299)throw new IllegalStateException("Webhook returned HTTP "+response.statusCode());}
}
