package com.nimbusbill.customer.service;

import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
import org.springframework.transaction.*; import org.springframework.transaction.support.TransactionTemplate;
import org.springframework.data.domain.Sort; import org.springframework.data.jpa.domain.Specification;

@Service @Transactional public class PaymentTransactionService {
 private final PaymentTransactionRepository transactions; private final TransactionStatusHistoryRepository history;
 private final TransactionChargeRepository charges; private final TransactionOutboxRepository outbox; private final AuditLogRepository audits; private final CustomerRepository customers; private final CustomerProductRepository customerProducts; private final PricingService pricing;
 private final TransactionTemplate requiresNew;
 public PaymentTransactionService(PaymentTransactionRepository t,TransactionStatusHistoryRepository h,TransactionChargeRepository c,TransactionOutboxRepository outbox,AuditLogRepository audits,CustomerRepository customers,CustomerProductRepository cp,PricingService pricing,PlatformTransactionManager manager){transactions=t;history=h;charges=c;this.outbox=outbox;this.audits=audits;this.customers=customers;customerProducts=cp;this.pricing=pricing;requiresNew=new TransactionTemplate(manager);requiresNew.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);}
 public PaymentTransactionResponse ingest(PaymentTransactionRequest request){return ingest(request,"REST");}
 public PaymentTransactionResponse ingest(PaymentTransactionRequest request,String source){
  String type=upper(request.transactionType()); String reference=request.clientReferenceId().trim();
  Customer customer=customers.findByIdForTransaction(request.customerId()).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+request.customerId()));
  var duplicate=transactions.findByCustomerIdAndClientReferenceIdAndTransactionType(request.customerId(),reference,type);
  if(duplicate.isPresent())return response(duplicate.get());
  PaymentTransaction tx=new PaymentTransaction();tx.setCustomer(customer);tx.setClientReferenceId(reference);tx.setProductCode(upper(request.productCode()));tx.setTransactionType(type);tx.setAmount(request.amount());tx.setCurrency(upper(request.currency()));tx.setSourceAccount(blank(request.sourceAccount()));tx.setDestinationAccount(blank(request.destinationAccount()));tx.setIngestionSource(source);tx.setStatus(PaymentTransactionStatus.RECEIVED);transactions.save(tx);record(tx,PaymentTransactionStatus.RECEIVED,"Transaction received via "+source);
  transition(tx,PaymentTransactionStatus.VALIDATING,"Validating customer, product, limits and pricing");
  String validationError=validate(customer,tx); if(validationError!=null)return reject(tx,validationError);
  PricingPreviewResponse quote; try{quote=pricing.priceCustomer(customer.getId(),tx.getProductCode(),tx.getAmount(),LocalDate.now());}catch(RuntimeException ex){return reject(tx,ex.getMessage());}
  if(!quote.currency().equalsIgnoreCase(tx.getCurrency()))return reject(tx,"Pricing currency "+quote.currency()+" does not match transaction currency "+tx.getCurrency());
  transition(tx,PaymentTransactionStatus.ACCEPTED,"Validation passed"); transition(tx,PaymentTransactionStatus.PROCESSING,"Processing transaction");
  TransactionCharge charge=new TransactionCharge();charge.setTransaction(tx);charge.setCustomer(customer);charge.setPricingPlanVersionId(quote.versionId());charge.setBaseFee(quote.baseFee());charge.setTaxAmount(quote.taxAmount());charge.setChargeAmount(quote.totalCharge());charge.setCurrency(quote.currency());charges.save(charge);
  tx.setCompletedAt(Instant.now());transition(tx,PaymentTransactionStatus.COMPLETED,"Transaction completed and charged once");event(tx,"TRANSACTION_COMPLETED");audit(tx,"TRANSACTION_COMPLETED",null,tx.getClientReferenceId());return response(tx);
 }
 private String validate(Customer customer,PaymentTransaction tx){
  if(customer.getStatus()!=CustomerStatus.ACTIVE)return "Customer is not active";
  CustomerProduct assignment=customerProducts.findByCustomerIdOrderByProductProductName(customer.getId()).stream().filter(cp->cp.getProduct().getProductCode().equalsIgnoreCase(tx.getProductCode())).findFirst().orElse(null);
  LocalDate today=LocalDate.now(); if(assignment==null||!assignment.isEnabled()||assignment.getActivationDate().isAfter(today)||(assignment.getExpiryDate()!=null&&assignment.getExpiryDate().isBefore(today)))return "Product is not enabled for this customer";
  PaymentProduct product=assignment.getProduct(); if(product.getStatus()!=ProductStatus.ACTIVE)return "Product is not active";
  if(!product.getTransactionTypes().isEmpty()&&product.getTransactionTypes().stream().noneMatch(x->x.equalsIgnoreCase(tx.getTransactionType())))return "Transaction type is not supported by product";
  if(!product.getCurrencies().isEmpty()&&product.getCurrencies().stream().noneMatch(x->x.equalsIgnoreCase(tx.getCurrency())))return "Currency is not supported by product";
  if(assignment.getTransactionLimit()!=null&&tx.getAmount().compareTo(assignment.getTransactionLimit())>0)return "Transaction limit exceeded";
  if(assignment.getDailyLimit()!=null){Instant start=LocalDate.now().atStartOfDay(ZoneOffset.UTC).toInstant();Instant end=LocalDate.now().plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant();if(transactions.completedAmount(customer.getId(),tx.getProductCode(),start,end).add(tx.getAmount()).compareTo(assignment.getDailyLimit())>0)return "Daily transaction limit exceeded";}
  return null;
 }
 private PaymentTransactionResponse reject(PaymentTransaction tx,String reason){tx.setFailureReason(reason);transition(tx,PaymentTransactionStatus.REJECTED,reason);event(tx,"TRANSACTION_REJECTED");audit(tx,"TRANSACTION_REJECTED",null,reason);return response(tx);}
 private void transition(PaymentTransaction tx,PaymentTransactionStatus status,String detail){tx.setStatus(status);transactions.save(tx);record(tx,status,detail);}
 private void record(PaymentTransaction tx,PaymentTransactionStatus status,String detail){TransactionStatusHistory h=new TransactionStatusHistory();h.setTransaction(tx);h.setStatus(status);h.setDetail(detail);history.save(h);}
 @Transactional(readOnly=true) public PaymentTransactionResponse get(UUID id){return response(transactions.findById(id).orElseThrow(()->new ResourceNotFoundException("Transaction not found: "+id)));}
 @Transactional(readOnly=true) public List<PaymentTransactionResponse> list(UUID customerId,PaymentTransactionStatus status,String product,String reference,LocalDate from,LocalDate to){Specification<PaymentTransaction> spec=(root,query,cb)->cb.equal(root.get("customer").get("id"),customerId);String normalizedProduct=blank(product);if(normalizedProduct!=null){String value=normalizedProduct.toUpperCase();spec=spec.and((root,query,cb)->cb.equal(root.get("productCode"),value));}String normalizedReference=blank(reference);if(normalizedReference!=null){String value="%"+normalizedReference.toLowerCase()+"%";spec=spec.and((root,query,cb)->cb.like(cb.lower(root.get("clientReferenceId")),value));}if(status!=null)spec=spec.and((root,query,cb)->cb.equal(root.get("status"),status));if(from!=null){Instant value=from.atStartOfDay(ZoneOffset.UTC).toInstant();spec=spec.and((root,query,cb)->cb.greaterThanOrEqualTo(root.get("createdAt"),value));}if(to!=null){Instant value=to.plusDays(1).atStartOfDay(ZoneOffset.UTC).toInstant();spec=spec.and((root,query,cb)->cb.lessThan(root.get("createdAt"),value));}return transactions.findAll(spec,Sort.by(Sort.Direction.DESC,"createdAt")).stream().map(this::response).toList();}
 public TransactionBatchResponse batch(List<PaymentTransactionRequest> requests){List<PaymentTransactionResponse> results=new ArrayList<>();List<String> errors=new ArrayList<>();for(PaymentTransactionRequest request:requests){try{PaymentTransactionResponse result=requiresNew.execute(status->ingest(request,"BATCH"));if(result!=null)results.add(result);}catch(RuntimeException ex){errors.add(request.clientReferenceId()+": "+ex.getMessage());}}return new TransactionBatchResponse(requests.size(),(int)results.stream().filter(x->x.status()==PaymentTransactionStatus.COMPLETED).count(),(int)results.stream().filter(x->x.status()==PaymentTransactionStatus.REJECTED).count(),errors.size(),errors,results);}
 @Transactional(readOnly=true) public TransactionSummaryResponse summary(UUID customerId){List<PaymentTransaction> items=transactions.findByCustomerIdOrderByCreatedAtDesc(customerId);var completed=items.stream().filter(t->t.getStatus()==PaymentTransactionStatus.COMPLETED&&"PAYMENT".equals(t.getTransactionKind())).toList();java.math.BigDecimal amount=completed.stream().map(PaymentTransaction::getAmount).reduce(java.math.BigDecimal.ZERO,java.math.BigDecimal::add);java.math.BigDecimal charge=completed.stream().map(t->charges.findByTransactionId(t.getId()).map(TransactionCharge::getChargeAmount).orElse(java.math.BigDecimal.ZERO)).reduce(java.math.BigDecimal.ZERO,java.math.BigDecimal::add);return new TransactionSummaryResponse(items.size(),completed.size(),items.stream().filter(t->t.getStatus()==PaymentTransactionStatus.REJECTED).count(),completed.stream().filter(t->"PENDING".equals(t.getReconciliationStatus())).count(),completed.stream().filter(t->"EXCEPTION".equals(t.getReconciliationStatus())).count(),amount,charge);}
 public PaymentTransactionResponse reverse(UUID id,ReversalRequest request){PaymentTransaction original=transactions.findById(id).orElseThrow(()->new ResourceNotFoundException("Transaction not found: "+id));if(original.getStatus()!=PaymentTransactionStatus.COMPLETED||!"PAYMENT".equals(original.getTransactionKind()))throw new ConflictException("Only completed payment transactions can be reversed");var existing=transactions.findByOriginalTransactionId(id);if(existing.isPresent())return response(existing.get());PaymentTransaction reversal=new PaymentTransaction();reversal.setCustomer(original.getCustomer());reversal.setClientReferenceId(request.clientReferenceId().trim());reversal.setProductCode(original.getProductCode());reversal.setTransactionType("REVERSAL_"+original.getTransactionType());reversal.setAmount(original.getAmount());reversal.setCurrency(original.getCurrency());reversal.setSourceAccount(original.getDestinationAccount());reversal.setDestinationAccount(original.getSourceAccount());reversal.setTransactionKind("REVERSAL");reversal.setOriginalTransaction(original);reversal.setStatus(PaymentTransactionStatus.COMPLETED);reversal.setCompletedAt(Instant.now());transactions.save(reversal);record(reversal,PaymentTransactionStatus.RECEIVED,"Reversal requested: "+blank(request.reason()));record(reversal,PaymentTransactionStatus.COMPLETED,"Original transaction reversed");charges.findByTransactionId(id).ifPresent(c->{c.setStatus("REVERSED");charges.save(c);});event(reversal,"TRANSACTION_REVERSED");return response(reversal);}
 public PaymentTransactionResponse reconcile(UUID id,ReconciliationRequest request){PaymentTransaction tx=transactions.findById(id).orElseThrow(()->new ResourceNotFoundException("Transaction not found: "+id));if(tx.getStatus()!=PaymentTransactionStatus.COMPLETED)throw new ConflictException("Only completed transactions can be reconciled");String old=tx.getReconciliationStatus();tx.setReconciliationStatus(request.status());tx.setExternalSettlementReference(blank(request.externalSettlementReference()));transactions.save(tx);record(tx,PaymentTransactionStatus.COMPLETED,"Reconciliation "+request.status()+": "+blank(request.detail()));event(tx,"TRANSACTION_RECONCILED");audit(tx,"TRANSACTION_RECONCILED",old,request.status());return response(tx);}
 private void event(PaymentTransaction tx,String type){TransactionOutbox e=new TransactionOutbox();e.setTransaction(tx);e.setEventType(type);e.setPayload("{\"transactionId\":\""+tx.getId()+"\",\"status\":\""+tx.getStatus()+"\"}");outbox.save(e);}
 private void audit(PaymentTransaction tx,String action,String oldValue,String newValue){AuditLog log=new AuditLog();log.setCustomerId(tx.getCustomer().getId());log.setAction(action);log.setOldValue(oldValue);log.setNewValue(newValue);log.setActor("transaction-service");audits.save(log);}
 private PaymentTransactionResponse response(PaymentTransaction tx){var charge=charges.findByTransactionId(tx.getId()).orElse(null);return new PaymentTransactionResponse(tx.getId(),tx.getCustomer().getId(),tx.getClientReferenceId(),tx.getProductCode(),tx.getTransactionType(),tx.getAmount(),tx.getCurrency(),tx.getSourceAccount(),tx.getDestinationAccount(),tx.getStatus(),tx.getFailureReason(),charge==null?null:charge.getBaseFee(),charge==null?null:charge.getTaxAmount(),charge==null?null:charge.getChargeAmount(),charge==null?null:charge.getPricingPlanVersionId(),charge==null?null:charge.getStatus(),tx.getTransactionKind(),tx.getIngestionSource(),tx.getOriginalTransaction()==null?null:tx.getOriginalTransaction().getId(),tx.getReconciliationStatus(),tx.getExternalSettlementReference(),tx.getCreatedAt(),tx.getCompletedAt(),history.findByTransactionIdOrderByCreatedAt(tx.getId()).stream().map(h->new PaymentTransactionResponse.StatusEntry(h.getStatus(),h.getDetail(),h.getCreatedAt())).toList());}
 private String upper(String v){return v.trim().toUpperCase();} private String blank(String v){return v==null||v.isBlank()?null:v.trim();}
}
