package com.nimbusbill.customer.service;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.exception.*; import com.nimbusbill.customer.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service @Transactional public class PricingService{
 private final PricingPlanRepository plans;private final PricingPlanVersionRepository versions;private final PaymentProductRepository products;
 public PricingService(PricingPlanRepository p,PricingPlanVersionRepository v,PaymentProductRepository products){plans=p;versions=v;this.products=products;}
 public PricingPlanResponse create(PricingPlanRequest r,String actor){validate(r);if(plans.existsByPlanCodeIgnoreCase(r.planCode()))throw new ConflictException("Pricing plan code already exists: "+r.planCode());PricingPlan p=new PricingPlan();p.setPlanCode(r.planCode().trim().toUpperCase());p.setPlanName(r.planName().trim());p.setDescription(blank(r.description()));plans.save(p);PricingPlanVersion v=buildVersion(p,1,r,actor);versions.save(v);return response(p);}
 @Transactional(readOnly=true) public List<PricingPlanResponse> list(){return plans.findAllByOrderByPlanName().stream().map(this::response).toList();}
 @Transactional(readOnly=true) public PricingPlanResponse get(UUID id){return response(findPlan(id));}
 public PricingPlanResponse submit(UUID planId,UUID versionId){PricingPlanVersion v=findVersion(planId,versionId);require(v,PricingVersionStatus.DRAFT,PricingVersionStatus.REJECTED);v.setStatus(PricingVersionStatus.PENDING_APPROVAL);versions.save(v);return response(v.getPlan());}
 public PricingPlanResponse approve(UUID planId,UUID versionId,String actor){PricingPlanVersion v=findVersion(planId,versionId);require(v,PricingVersionStatus.PENDING_APPROVAL);if(v.getCreatedBy().equalsIgnoreCase(actor))throw new ConflictException("Maker-checker rule: creator cannot approve this pricing version");v.setStatus(PricingVersionStatus.APPROVED);v.setApprovedBy(actor);v.setApprovedAt(Instant.now());versions.save(v);return response(v.getPlan());}
 public PricingPlanResponse reject(UUID planId,UUID versionId,String actor){PricingPlanVersion v=findVersion(planId,versionId);require(v,PricingVersionStatus.PENDING_APPROVAL);if(v.getCreatedBy().equalsIgnoreCase(actor))throw new ConflictException("Maker-checker rule: creator cannot reject this pricing version");v.setStatus(PricingVersionStatus.REJECTED);v.setApprovedBy(actor);v.setApprovedAt(Instant.now());versions.save(v);return response(v.getPlan());}
 public PricingPlanResponse activate(UUID planId,UUID versionId){PricingPlanVersion v=findVersion(planId,versionId);require(v,PricingVersionStatus.APPROVED);versions.findFirstByPlanIdAndStatusOrderByVersionNumberDesc(planId,PricingVersionStatus.ACTIVE).ifPresent(old->{old.setStatus(PricingVersionStatus.EXPIRED);versions.save(old);});v.setStatus(PricingVersionStatus.ACTIVE);versions.save(v);return response(v.getPlan());}
 @Transactional(readOnly=true) public PricingPreviewResponse preview(PricingPreviewRequest r){List<PricingPlanVersion> matches=versions.active(r.planId(),r.transactionDate());if(matches.isEmpty())throw new ResourceNotFoundException("No active pricing version for transaction date");PricingPlanVersion v=matches.getFirst();PricingRule rule=v.getRules().stream().filter(x->x.getProduct().getProductCode().equalsIgnoreCase(r.productCode())).findFirst().orElseThrow(()->new ResourceNotFoundException("No pricing rule for product: "+r.productCode()));BigDecimal base=calculate(rule,r.amount());base=clamp(base,rule.getMinimumFee(),rule.getMaximumFee()).setScale(4,RoundingMode.HALF_UP);BigDecimal tax=base.multiply(rule.getTaxRate()).divide(new BigDecimal("100"),4,RoundingMode.HALF_UP);return new PricingPreviewResponse(v.getPlan().getId(),v.getId(),v.getVersionNumber(),rule.getProduct().getProductCode(),rule.getChargeType(),r.amount(),base,rule.getTaxRate(),tax,base.add(tax),v.getCurrency());}
 private BigDecimal calculate(PricingRule r,BigDecimal amount){return switch(r.getChargeType()){case FIXED->zero(r.getFixedFee());case PERCENTAGE->percent(amount,r.getPercentageRate());case HYBRID->zero(r.getFixedFee()).add(percent(amount,r.getPercentageRate()));case SLAB->{PricingSlab s=r.getSlabs().stream().filter(x->amount.compareTo(x.getLowerBound())>=0&&(x.getUpperBound()==null||amount.compareTo(x.getUpperBound())<=0)).findFirst().orElseThrow(()->new IllegalArgumentException("No pricing slab matches amount"));yield zero(s.getFlatFee()).add(percent(amount,s.getPercentageRate()));}};}
 private PricingPlanVersion buildVersion(PricingPlan p,int number,PricingPlanRequest r,String actor){PricingPlanVersion v=new PricingPlanVersion();v.setPlan(p);v.setVersionNumber(number);v.setCurrency(r.currency().toUpperCase());v.setEffectiveFrom(r.effectiveFrom());v.setEffectiveTo(r.effectiveTo());v.setStatus(PricingVersionStatus.DRAFT);v.setCreatedBy(actor);for(PricingRuleRequest rr:r.rules()){PricingRule rule=new PricingRule();rule.setVersion(v);rule.setProduct(products.findById(rr.productId()).orElseThrow(()->new ResourceNotFoundException("Product not found: "+rr.productId())));rule.setChargeType(rr.chargeType());rule.setFixedFee(rr.fixedFee());rule.setPercentageRate(rr.percentageRate());rule.setMinimumFee(rr.minimumFee());rule.setMaximumFee(rr.maximumFee());rule.setTaxRate(rr.taxRate());rule.setPriority(rr.priority());if(rr.slabs()!=null)for(PricingSlabRequest sr:rr.slabs()){PricingSlab s=new PricingSlab();s.setRule(rule);s.setLowerBound(sr.lowerBound());s.setUpperBound(sr.upperBound());s.setFlatFee(sr.flatFee());s.setPercentageRate(sr.percentageRate());s.setSequenceNo(sr.sequenceNo());rule.getSlabs().add(s);}v.getRules().add(rule);}return v;}
 private void validate(PricingPlanRequest r){if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw new IllegalArgumentException("effectiveTo cannot precede effectiveFrom");for(PricingRuleRequest rule:r.rules()){if(rule.minimumFee()!=null&&rule.maximumFee()!=null&&rule.minimumFee().compareTo(rule.maximumFee())>0)throw new IllegalArgumentException("minimumFee cannot exceed maximumFee");if(rule.chargeType()==PricingUnit.FIXED&&rule.fixedFee()==null)throw new IllegalArgumentException("fixedFee is required for FIXED rules");if(rule.chargeType()==PricingUnit.PERCENTAGE&&rule.percentageRate()==null)throw new IllegalArgumentException("percentageRate is required for PERCENTAGE rules");if(rule.chargeType()==PricingUnit.SLAB&&(rule.slabs()==null||rule.slabs().isEmpty()))throw new IllegalArgumentException("At least one slab is required for SLAB rules");validateSlabs(rule.slabs());}}
 private void validateSlabs(List<PricingSlabRequest> slabs){if(slabs==null)return;List<PricingSlabRequest> sorted=slabs.stream().sorted(Comparator.comparing(PricingSlabRequest::lowerBound)).toList();for(int i=0;i<sorted.size();i++){PricingSlabRequest s=sorted.get(i);if(s.upperBound()!=null&&s.upperBound().compareTo(s.lowerBound())<=0)throw new IllegalArgumentException("Slab upperBound must exceed lowerBound");if(i>0){PricingSlabRequest prev=sorted.get(i-1);if(prev.upperBound()==null||s.lowerBound().compareTo(prev.upperBound())<=0)throw new IllegalArgumentException("Pricing slabs cannot overlap");}}}
 private PricingPlan findPlan(UUID id){return plans.findById(id).orElseThrow(()->new ResourceNotFoundException("Pricing plan not found: "+id));}private PricingPlanVersion findVersion(UUID plan,UUID id){PricingPlanVersion v=versions.findById(id).orElseThrow(()->new ResourceNotFoundException("Pricing version not found: "+id));if(!v.getPlan().getId().equals(plan))throw new ResourceNotFoundException("Pricing version not found for plan");return v;}private void require(PricingPlanVersion v,PricingVersionStatus... states){if(Arrays.stream(states).noneMatch(x->x==v.getStatus()))throw new ConflictException("Invalid pricing lifecycle transition from "+v.getStatus());}
 private PricingPlanResponse response(PricingPlan p){List<PricingPlanResponse.Version> vs=versions.findByPlanIdOrderByVersionNumberDesc(p.getId()).stream().map(v->new PricingPlanResponse.Version(v.getId(),v.getVersionNumber(),v.getCurrency(),v.getEffectiveFrom(),v.getEffectiveTo(),v.getStatus(),v.getCreatedBy(),v.getApprovedBy(),v.getCreatedAt(),v.getApprovedAt(),v.getRules().stream().map(r->new PricingPlanResponse.Rule(r.getId(),r.getProduct().getId(),r.getProduct().getProductCode(),r.getProduct().getProductName(),r.getChargeType(),r.getFixedFee(),r.getPercentageRate(),r.getMinimumFee(),r.getMaximumFee(),r.getTaxRate(),r.getPriority(),r.getSlabs().stream().map(s->new PricingPlanResponse.Slab(s.getId(),s.getLowerBound(),s.getUpperBound(),s.getFlatFee(),s.getPercentageRate(),s.getSequenceNo())).toList())).toList())).toList();return new PricingPlanResponse(p.getId(),p.getPlanCode(),p.getPlanName(),p.getDescription(),vs);}
 private BigDecimal percent(BigDecimal amount,BigDecimal rate){return rate==null?BigDecimal.ZERO:amount.multiply(rate).divide(new BigDecimal("100"),8,RoundingMode.HALF_UP);}private BigDecimal zero(BigDecimal v){return v==null?BigDecimal.ZERO:v;}private BigDecimal clamp(BigDecimal v,BigDecimal min,BigDecimal max){if(min!=null&&v.compareTo(min)<0)v=min;if(max!=null&&v.compareTo(max)>0)v=max;return v;}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
}
