package com.nimbusbill.customer.service;
import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.repository.*; import org.slf4j.*; import org.springframework.data.domain.PageRequest; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class TransactionOutboxDispatcher {
 private static final Logger log=LoggerFactory.getLogger(TransactionOutboxDispatcher.class); private static final int MAX_ATTEMPTS=5; private final TransactionOutboxRepository repository; private final NotificationOutboxRepository notifications;
 public TransactionOutboxDispatcher(TransactionOutboxRepository repository,NotificationOutboxRepository notifications){this.repository=repository;this.notifications=notifications;}
 @Scheduled(fixedDelayString="${app.transactions.outbox-poll-delay-ms:3000}") @Transactional public void publish(){repository.ready(List.of("PENDING","FAILED"),Instant.now(),PageRequest.of(0,50)).forEach(this::deliver);}
 private void deliver(TransactionOutbox event){event.setStatus("PROCESSING");event.setAttemptCount(event.getAttemptCount()+1);repository.save(event);try{log.info("Transaction event published type={} transactionId={} payload={}",event.getEventType(),event.getTransaction().getId(),event.getPayload());event.setStatus("PUBLISHED");event.setPublishedAt(Instant.now());event.setNextAttemptAt(null);event.setLastError(null);}catch(RuntimeException ex){event.setLastError(ex.getMessage());if(event.getAttemptCount()>=MAX_ATTEMPTS){event.setStatus("DEAD");event.setNextAttemptAt(null);alert(event);}else{event.setStatus("FAILED");event.setNextAttemptAt(Instant.now().plusSeconds((long)Math.pow(2,event.getAttemptCount())*10));}}repository.save(event);}
 private void alert(TransactionOutbox event){NotificationOutbox n=new NotificationOutbox();n.setEventType("TRANSACTION_OUTBOX_DEAD");n.setEntityType("PAYMENT_TRANSACTION");n.setEntityId(event.getTransaction().getId());n.setRecipientRole("OPERATIONS");n.setSubject("Transaction event requires intervention");n.setMessage(event.getEventType()+" exhausted retries: "+event.getLastError());notifications.save(n);}
 public void retry(UUID id){TransactionOutbox event=repository.findById(id).orElseThrow();event.setStatus("PENDING");event.setNextAttemptAt(Instant.now());event.setLastError(null);repository.save(event);}
}
