package com.nimbusbill.customer.controller;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.entity.*; import com.nimbusbill.customer.service.PaymentTransactionService; import jakarta.validation.Valid; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.net.URI; import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/api/v1/transactions") public class PaymentTransactionController {
 private final PaymentTransactionService service; public PaymentTransactionController(PaymentTransactionService service){this.service=service;}
 @PostMapping @PreAuthorize("hasAnyRole('ADMIN','OPERATIONS')") ResponseEntity<PaymentTransactionResponse> ingest(@Valid @RequestBody PaymentTransactionRequest request){var result=service.ingest(request);HttpStatus status=result.status()==PaymentTransactionStatus.REJECTED?HttpStatus.UNPROCESSABLE_ENTITY:HttpStatus.CREATED;return ResponseEntity.status(status).location(URI.create("/api/v1/transactions/"+result.id())).body(result);}
 @GetMapping @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") List<PaymentTransactionResponse> list(@RequestParam UUID customerId,@RequestParam(required=false) PaymentTransactionStatus status,@RequestParam(required=false) String product,@RequestParam(required=false) String reference,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to){return service.list(customerId,status,product,reference,from,to);}
 @GetMapping("/{id}") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") PaymentTransactionResponse get(@PathVariable UUID id){return service.get(id);}
 @PostMapping("/batch") @PreAuthorize("hasAnyRole('ADMIN','OPERATIONS')") TransactionBatchResponse batch(@RequestBody @jakarta.validation.Valid List<@Valid PaymentTransactionRequest> requests){return service.batch(requests);}
 @PostMapping("/events") @PreAuthorize("hasAnyRole('ADMIN','OPERATIONS')") PaymentTransactionResponse event(@Valid @RequestBody PaymentTransactionRequest request){return service.ingest(request,"EVENT");}
 @GetMapping("/summary") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") TransactionSummaryResponse summary(@RequestParam UUID customerId){return service.summary(customerId);}
 @PostMapping("/{id}/reversal") @PreAuthorize("hasAnyRole('ADMIN','OPERATIONS')") PaymentTransactionResponse reverse(@PathVariable UUID id,@Valid @RequestBody ReversalRequest request){return service.reverse(id,request);}
 @PostMapping("/{id}/reconciliation") @PreAuthorize("hasAnyRole('ADMIN','FINANCE','OPERATIONS')") PaymentTransactionResponse reconcile(@PathVariable UUID id,@Valid @RequestBody ReconciliationRequest request){return service.reconcile(id,request);}
}
