package com.nimbusbill.customer.controller;
import com.nimbusbill.customer.dto.*; import com.nimbusbill.customer.service.PricingService; import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.net.URI; import java.security.Principal; import java.util.*;
@RestController @RequestMapping("/api/v1") public class PricingController{
 private final PricingService service;public PricingController(PricingService service){this.service=service;}
 @PostMapping("/pricing-plans") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER')") ResponseEntity<PricingPlanResponse> create(@Valid @RequestBody PricingPlanRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){PricingPlanResponse p=service.create(r,actor(principal,localActor));return ResponseEntity.created(URI.create("/api/v1/pricing-plans/"+p.id())).body(p);}
 @GetMapping("/pricing-plans") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") List<PricingPlanResponse> list(){return service.list();}
 @GetMapping("/pricing-plans/{id}") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") PricingPlanResponse get(@PathVariable UUID id){return service.get(id);}
 @PostMapping("/pricing-plans/{planId}/versions/{versionId}/submit") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER')") PricingPlanResponse submit(@PathVariable UUID planId,@PathVariable UUID versionId,@RequestBody(required=false) ApprovalActionRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){return service.submit(planId,versionId,actor(principal,localActor),r==null?null:r.comments());}
 @PostMapping("/pricing-plans/{planId}/versions/{versionId}/approve") @PreAuthorize("hasAnyRole('ADMIN','FINANCE')") PricingPlanResponse approve(@PathVariable UUID planId,@PathVariable UUID versionId,@RequestBody(required=false) ApprovalActionRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){return service.approve(planId,versionId,actor(principal,localActor),r==null?null:r.comments());}
 @PostMapping("/pricing-plans/{planId}/versions/{versionId}/reject") @PreAuthorize("hasAnyRole('ADMIN','FINANCE')") PricingPlanResponse reject(@PathVariable UUID planId,@PathVariable UUID versionId,@RequestBody(required=false) ApprovalActionRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){return service.reject(planId,versionId,actor(principal,localActor),r==null?null:r.comments());}
 @PostMapping("/pricing-plans/{planId}/versions/{versionId}/activate") @PreAuthorize("hasRole('ADMIN')") PricingPlanResponse activate(@PathVariable UUID planId,@PathVariable UUID versionId,@RequestBody(required=false) ApprovalActionRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){return service.activate(planId,versionId,actor(principal,localActor),r==null?null:r.comments());}
 @PostMapping("/pricing-plans/{planId}/versions/{versionId}/clone") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER')") PricingPlanResponse cloneVersion(@PathVariable UUID planId,@PathVariable UUID versionId,@Valid @RequestBody ClonePricingVersionRequest r,Principal principal,@RequestHeader(value="X-Actor",required=false) String localActor){return service.cloneVersion(planId,versionId,r,actor(principal,localActor));}
 @PostMapping("/pricing/preview") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','OPERATIONS','AUDITOR','READ_ONLY')") PricingPreviewResponse preview(@Valid @RequestBody PricingPreviewRequest r){return service.preview(r);}
 @GetMapping("/pricing-plans/{planId}/history") @PreAuthorize("hasAnyRole('ADMIN','BILLING_MANAGER','FINANCE','AUDITOR','READ_ONLY')") List<PricingAuditResponse> history(@PathVariable UUID planId){return service.history(planId);}
 private String actor(Principal p,String local){return p==null||"local-admin".equals(p.getName())?(local==null||local.isBlank()?"local-admin":local):p.getName();}
}
