import {useEffect,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Checkbox,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,MenuItem,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {listCustomers} from '../api/customers'; import {listBillingRuns} from '../api/billing';
import {addAdjustment,deliverInvoice,downloadInvoiceDocument,generateInvoice,getTaxProfile,Invoice,invoiceAction,lifecycleAction,listDeliveries,listInvoices,saveTaxProfile} from '../api/invoices';
const today=new Date().toISOString().slice(0,10);
const color=(s:string)=>s==='ISSUED'||s==='PAID'?'success':s==='APPROVED'?'primary':s==='CANCELLED'||s==='REJECTED'?'error':s==='DISPUTED'||s==='OVERDUE'?'warning':'default';
export default function Invoices(){
 const cache=useQueryClient();const [customerId,setCustomerId]=useState('');const [selected,setSelected]=useState<Invoice|null>(null);
 const [tax,setTax]=useState({taxIdentifier:'',taxCountry:'IN',taxRegion:'',placeOfSupply:'',defaultTaxRate:18,taxExempt:false,effectiveFrom:today});
 const [adjustment,setAdjustment]=useState({adjustmentType:'CREDIT' as 'CREDIT'|'DEBIT',amount:0,reason:''});const [delivery,setDelivery]=useState({channel:'EMAIL' as 'EMAIL'|'WEBHOOK'|'API',destination:''});
 const customers=useQuery({queryKey:['customers','invoice-operations'],queryFn:()=>listCustomers('','ACTIVE')});
 const runs=useQuery({queryKey:['billing-runs',customerId],queryFn:()=>listBillingRuns(customerId),enabled:Boolean(customerId)});
 const invoices=useQuery({queryKey:['invoices',customerId],queryFn:()=>listInvoices(customerId),enabled:Boolean(customerId)});
 const taxProfile=useQuery({queryKey:['tax-profile',customerId],queryFn:()=>getTaxProfile(customerId),enabled:Boolean(customerId),retry:false});
 const deliveries=useQuery({queryKey:['invoice-deliveries',selected?.id],queryFn:()=>listDeliveries(selected!.id),enabled:Boolean(selected?.id)});
 useEffect(()=>{if(taxProfile.data)setTax({taxIdentifier:taxProfile.data.taxIdentifier??'',taxCountry:taxProfile.data.taxCountry,taxRegion:taxProfile.data.taxRegion??'',placeOfSupply:taxProfile.data.placeOfSupply??'',defaultTaxRate:taxProfile.data.defaultTaxRate,taxExempt:taxProfile.data.taxExempt,effectiveFrom:taxProfile.data.effectiveFrom})},[taxProfile.data]);
 const refresh=async()=>{await cache.invalidateQueries({queryKey:['invoices',customerId]});const fresh=await cache.fetchQuery({queryKey:['invoices',customerId],queryFn:()=>listInvoices(customerId)});if(selected)setSelected(fresh.find(i=>i.id===selected.id)??null)};
 const generate=useMutation({mutationFn:generateInvoice,onSuccess:async v=>{setSelected(v);await refresh()}});
 const standard=useMutation({mutationFn:({i,a}:{i:Invoice;a:'submit'|'approve'|'issue'|'cancel'})=>invoiceAction(i.id,a,a+' from invoice operations'),onSuccess:refresh});
 const lifecycle=useMutation({mutationFn:({i,a}:{i:Invoice;a:'reject'|'reopen'|'dispute'|'paid'})=>lifecycleAction(i.id,a,a+' from invoice operations'),onSuccess:refresh});
 const saveTax=useMutation({mutationFn:()=>saveTaxProfile(customerId,tax),onSuccess:()=>cache.invalidateQueries({queryKey:['tax-profile',customerId]})});
 const adjust=useMutation({mutationFn:()=>addAdjustment(selected!.id,adjustment),onSuccess:async()=>{setAdjustment({adjustmentType:'CREDIT',amount:0,reason:''});await refresh()}});
 const deliver=useMutation({mutationFn:()=>deliverInvoice(selected!.id,delivery.channel,delivery.destination),onSuccess:async()=>{setDelivery(v=>({...v,destination:''}));await cache.invalidateQueries({queryKey:['invoice-deliveries',selected?.id]})}});
 const error=customers.error||runs.error||invoices.error||generate.error||standard.error||lifecycle.error||saveTax.error||adjust.error||deliver.error;const invoiced=new Set(invoices.data?.map(i=>i.billingRunId));
 return <Stack spacing={3}><Box><Typography variant="h4">Invoice operations</Typography><Typography color="text.secondary">Configure tax, generate invoices, control approval, adjustments, payment and delivery.</Typography></Box>{error&&<Alert severity="error">{error.message}</Alert>}
 <TextField select label="Customer" value={customerId} onChange={e=>{setCustomerId(e.target.value);setSelected(null)}} sx={{maxWidth:520}}>{customers.data?.content.map(c=><MenuItem key={c.id} value={c.id}>{c.customerName} · {c.customerCode}</MenuItem>)}</TextField>
 {customerId&&<><Card><CardContent><Typography variant="h6">Customer tax profile</Typography><Typography color="text.secondary" variant="body2" mb={2}>Used for invoice tax reporting and place-of-supply controls.</Typography><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField label="Tax identifier / GSTIN" value={tax.taxIdentifier} onChange={e=>setTax(v=>({...v,taxIdentifier:e.target.value}))}/><TextField label="Country" value={tax.taxCountry} onChange={e=>setTax(v=>({...v,taxCountry:e.target.value.toUpperCase()}))}/><TextField label="Region / state" value={tax.taxRegion} onChange={e=>setTax(v=>({...v,taxRegion:e.target.value}))}/><TextField label="Place of supply" value={tax.placeOfSupply} onChange={e=>setTax(v=>({...v,placeOfSupply:e.target.value}))}/><TextField type="number" label="Tax rate %" value={tax.defaultTaxRate} onChange={e=>setTax(v=>({...v,defaultTaxRate:Number(e.target.value)}))}/><FormControlLabel control={<Checkbox checked={tax.taxExempt} onChange={e=>setTax(v=>({...v,taxExempt:e.target.checked}))}/>} label="Tax exempt"/><Button variant="contained" disabled={saveTax.isPending||tax.taxCountry.length!==2} onClick={()=>saveTax.mutate()}>Save tax profile</Button></Stack></CardContent></Card>
 <Card><CardContent><Typography variant="h6" mb={2}>Completed billing runs</Typography><Table><TableHead><TableRow>{['Completed','Charges','Subtotal','Tax','Total','Action'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{runs.data?.filter(r=>r.status==='COMPLETED').map(r=><TableRow key={r.id}><TableCell>{r.completedAt?new Date(r.completedAt).toLocaleString():'—'}</TableCell><TableCell>{r.chargeCount}</TableCell><TableCell>{r.subtotal}</TableCell><TableCell>{r.taxTotal}</TableCell><TableCell>{r.grandTotal}</TableCell><TableCell><Button variant="contained" disabled={generate.isPending||invoiced.has(r.id)} onClick={()=>generate.mutate(r.id)}>{invoiced.has(r.id)?'Generated':'Generate'}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
 <Card><CardContent><Typography variant="h6" mb={2}>Invoices</Typography><Table><TableHead><TableRow>{['Invoice','Date','Due','Status','Adjustments','Total','Actions'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{invoices.data?.map(i=><TableRow hover key={i.id}><TableCell><Button onClick={()=>setSelected(i)}>{i.invoiceNumber}</Button></TableCell><TableCell>{i.invoiceDate}</TableCell><TableCell>{i.dueDate}</TableCell><TableCell><Chip size="small" label={i.status} color={color(i.status)}/></TableCell><TableCell>{i.adjustmentTotal}</TableCell><TableCell><b>{i.currency} {i.grandTotal}</b></TableCell><TableCell><Stack direction="row">{i.status==='DRAFT'&&<Button onClick={()=>standard.mutate({i,a:'submit'})}>Submit</Button>}{i.status==='SUBMITTED'&&<><Button onClick={()=>standard.mutate({i,a:'approve'})}>Approve</Button><Button color="error" onClick={()=>lifecycle.mutate({i,a:'reject'})}>Reject</Button></>}{i.status==='REJECTED'&&<Button onClick={()=>lifecycle.mutate({i,a:'reopen'})}>Reopen</Button>}{i.status==='APPROVED'&&<Button onClick={()=>standard.mutate({i,a:'issue'})}>Issue</Button>}{i.status==='ISSUED'&&<><Button color="warning" onClick={()=>lifecycle.mutate({i,a:'dispute'})}>Dispute</Button><Button color="success" onClick={()=>lifecycle.mutate({i,a:'paid'})}>Mark paid</Button></>}{['OVERDUE','DISPUTED'].includes(i.status)&&<Button color="success" onClick={()=>lifecycle.mutate({i,a:'paid'})}>Mark paid</Button>}</Stack></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></>}
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="md"><DialogTitle>{selected?.invoiceNumber}</DialogTitle><DialogContent>{selected&&<Stack spacing={2} mt={1}><Stack direction="row" justifyContent="space-between"><Chip label={selected.status} color={color(selected.status)}/><Typography variant="h6">{selected.currency} {selected.grandTotal}</Typography></Stack><Table size="small"><TableHead><TableRow>{['Product','Description','Base','Tax','Total'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{selected.lines.map(l=><TableRow key={l.id}><TableCell>{l.productCode}</TableCell><TableCell>{l.description}</TableCell><TableCell>{l.baseAmount}</TableCell><TableCell>{l.taxAmount}</TableCell><TableCell>{l.totalAmount}</TableCell></TableRow>)}</TableBody></Table>{['DRAFT','REJECTED'].includes(selected.status)&&<Card variant="outlined"><CardContent><Typography fontWeight={800} mb={1}>Add adjustment</Typography><Stack direction="row" spacing={1}><TextField select label="Type" value={adjustment.adjustmentType} onChange={e=>setAdjustment(v=>({...v,adjustmentType:e.target.value as 'CREDIT'|'DEBIT'}))}><MenuItem value="CREDIT">Credit</MenuItem><MenuItem value="DEBIT">Debit</MenuItem></TextField><TextField type="number" label="Amount" value={adjustment.amount} onChange={e=>setAdjustment(v=>({...v,amount:Number(e.target.value)}))}/><TextField fullWidth label="Reason" value={adjustment.reason} onChange={e=>setAdjustment(v=>({...v,reason:e.target.value}))}/><Button disabled={adjustment.amount<=0||!adjustment.reason} onClick={()=>adjust.mutate()}>Add</Button></Stack></CardContent></Card>}{selected.status==='ISSUED'&&<Card variant="outlined"><CardContent><Typography fontWeight={800} mb={1}>Deliver invoice</Typography><Stack direction="row" spacing={1}><TextField select label="Channel" value={delivery.channel} onChange={e=>setDelivery(v=>({...v,channel:e.target.value as 'EMAIL'|'WEBHOOK'|'API'}))}><MenuItem value="EMAIL">Email</MenuItem><MenuItem value="WEBHOOK">Webhook</MenuItem><MenuItem value="API">API</MenuItem></TextField><TextField fullWidth label="Destination" value={delivery.destination} onChange={e=>setDelivery(v=>({...v,destination:e.target.value}))}/><Button disabled={!delivery.destination} onClick={()=>deliver.mutate()}>Deliver</Button></Stack>{deliveries.data?.map(d=><Typography variant="caption" display="block" mt={1} key={d.id}>{d.channel} → {d.destination} · {d.status}</Typography>)}</CardContent></Card>}</Stack>}</DialogContent><DialogActions>{selected&&<Button variant="outlined" onClick={()=>downloadInvoiceDocument(selected.id,selected.invoiceNumber)}>Download PDF</Button>}<Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></Dialog>
 </Stack>
}
