import { useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import ContentCopyRounded from '@mui/icons-material/ContentCopyRounded';
import CompareArrowsRounded from '@mui/icons-material/CompareArrowsRounded';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { clonePricingVersion, listPricingPlans, PricingVersion } from '../api/pricing';
import { StatusChip } from '../components/StatusChip';

const today=new Date().toISOString().slice(0,10);
export default function PricingVersions(){
 const client=useQueryClient();const plans=useQuery({queryKey:['pricing-plans'],queryFn:listPricingPlans});const [planId,setPlanId]=useState('');const [source,setSource]=useState<PricingVersion|null>(null);const [effectiveFrom,setEffectiveFrom]=useState(today);const [effectiveTo,setEffectiveTo]=useState('');const selected=useMemo(()=>plans.data?.find(p=>p.id===planId),[plans.data,planId]);
 const clone=useMutation({mutationFn:()=>clonePricingVersion(planId,source!.id,effectiveFrom,effectiveTo||null),onSuccess:async()=>{await client.invalidateQueries({queryKey:['pricing-plans']});setSource(null);}});
 return <Stack spacing={3}><Box><Typography variant="h4">Pricing version history</Typography><Typography color="text.secondary">Compare plan versions and clone any historical version into a new draft.</Typography></Box>{(plans.error||clone.error)&&<Alert severity="error">{(plans.error||clone.error)!.message}</Alert>}<Card><CardContent><TextField select fullWidth label="Pricing plan" value={planId} onChange={e=>setPlanId(e.target.value)}>{plans.data?.map(p=><MenuItem key={p.id} value={p.id}>{p.planName} · {p.planCode}</MenuItem>)}</TextField></CardContent></Card>{selected&&<Card><CardContent><Stack direction="row" spacing={1} alignItems="center" mb={2}><CompareArrowsRounded color="primary"/><Typography variant="h6">{selected.planName} versions</Typography></Stack><Table><TableHead><TableRow>{['Version','Status','Currency','Effective period','Rules','Created by','Approved by','Action'].map(x=><TableCell key={x} sx={{fontWeight:800}}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{selected.versions.map(v=><TableRow key={v.id}><TableCell>v{v.versionNumber}</TableCell><TableCell><StatusChip status={v.status}/></TableCell><TableCell>{v.currency}</TableCell><TableCell>{v.effectiveFrom} → {v.effectiveTo??'Open ended'}</TableCell><TableCell>{v.rules.map(r=><Box key={r.id}><Typography variant="body2" fontWeight={700}>{r.productCode}: {r.chargeType}</Typography><Typography variant="caption" color="text.secondary">Fixed {r.fixedFee??'—'} · Rate {r.percentageRate??'—'}% · Min {r.minimumFee??'—'} · Max {r.maximumFee??'—'}</Typography></Box>)}</TableCell><TableCell>{v.createdBy}</TableCell><TableCell>{v.approvedBy??'—'}</TableCell><TableCell><Button startIcon={<ContentCopyRounded/>} onClick={()=>{setSource(v);setEffectiveFrom(today);setEffectiveTo('')}}>Clone</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}<Dialog open={Boolean(source)} onClose={()=>setSource(null)} fullWidth maxWidth="sm"><DialogTitle>Clone version {source?.versionNumber}</DialogTitle><DialogContent><Typography color="text.secondary" mb={2}>Rules and slabs will be copied into a new draft version.</Typography><Stack spacing={2}><TextField required fullWidth type="date" label="Effective from" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField fullWidth type="date" label="Effective to" value={effectiveTo} onChange={e=>setEffectiveTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setSource(null)}>Cancel</Button><Button variant="contained" disabled={!effectiveFrom||clone.isPending} onClick={()=>clone.mutate()}>{clone.isPending?'Cloning…':'Create draft version'}</Button></DialogActions></Dialog></Stack>;
}
