import {FormEvent,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,MenuItem,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {listCustomers} from '../api/customers'; import {createTransaction,createTransactionBatch,getTransactionSummary,listTransactions,PaymentTransaction,PaymentTransactionInput,reconcileTransaction,reverseTransaction} from '../api/transactions';
import {parseCsv,requireBatchColumns} from '../utils/csv';
const newReference=()=>`PAY-${Date.now()}-${crypto.randomUUID().slice(0,6)}`;
export default function Transactions(){
 const client=useQueryClient(); const [customerId,setCustomerId]=useState('');
 const [form,setForm]=useState({clientReferenceId:newReference(),productCode:'UPI',transactionType:'UPI',amount:0,currency:'INR',sourceAccount:'',destinationAccount:''}); const [filters,setFilters]=useState({status:'',product:'',reference:'',from:'',to:''}); const [selected,setSelected]=useState<PaymentTransaction|null>(null); const [batchResult,setBatchResult]=useState('');
 const customers=useQuery({queryKey:['customers','transactions'],queryFn:()=>listCustomers('','ACTIVE')});
 const transactions=useQuery({queryKey:['transactions',customerId,filters],queryFn:()=>listTransactions(customerId,filters),enabled:Boolean(customerId)});
 const summary=useQuery({queryKey:['transaction-summary',customerId],queryFn:()=>getTransactionSummary(customerId),enabled:Boolean(customerId)});
 const ingest=useMutation({mutationFn:()=>createTransaction({...form,customerId}),onSuccess:async()=>{await client.invalidateQueries({queryKey:['transactions',customerId]});setForm(v=>({...v,clientReferenceId:newReference(),amount:0}));}});
 const reverse=useMutation({mutationFn:(t:PaymentTransaction)=>reverseTransaction(t.id,`REV-${t.clientReferenceId}`,`Reversed from operations workspace`),onSuccess:async result=>{setSelected(result);await client.invalidateQueries({queryKey:['transactions',customerId]});}});
 const reconcile=useMutation({mutationFn:({t,status}:{t:PaymentTransaction;status:'MATCHED'|'EXCEPTION'})=>reconcileTransaction(t.id,status,`SETTLE-${t.clientReferenceId}`,`Marked ${status.toLowerCase()} from workspace`),onSuccess:async result=>{setSelected(result);await client.invalidateQueries({queryKey:['transactions',customerId]});}});
 const batch=useMutation({mutationFn:(items:PaymentTransactionInput[])=>createTransactionBatch(items),onSuccess:async result=>{setBatchResult(`${result.received} received · ${result.completed} completed · ${result.rejected} rejected · ${result.failed} failed${result.errors.length?` · ${result.errors.join('; ')}`:''}`);await client.invalidateQueries({queryKey:['transactions',customerId]});}});
 const error=customers.error||transactions.error||summary.error||ingest.error||reverse.error||reconcile.error||batch.error; const submit=(e:FormEvent)=>{e.preventDefault();ingest.mutate();};
 const importBatch=async(file:File)=>{try{const rows=requireBatchColumns(parseCsv(await file.text()));const items=rows.map(row=>{const [clientReferenceId,productCode,transactionType,amount,currency,sourceAccount='',destinationAccount='']=row;return {customerId,clientReferenceId,productCode,transactionType,amount:Number(amount),currency,sourceAccount,destinationAccount}});batch.mutate(items)}catch(error){setBatchResult(error instanceof Error?error.message:'Invalid CSV file')}};
 const exportCsv=()=>{const header='id,clientReferenceId,productCode,transactionType,amount,currency,status,charge,reconciliationStatus,createdAt';const rows=(transactions.data??[]).map(t=>[t.id,t.clientReferenceId,t.productCode,t.transactionType,t.amount,t.currency,t.status,t.totalCharge??'',t.reconciliationStatus,t.createdAt].join(','));const url=URL.createObjectURL(new Blob([[header,...rows].join('\n')],{type:'text/csv'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='nimbusbill-transactions.csv';anchor.click();URL.revokeObjectURL(url)};
 return <Stack spacing={3}><Box><Typography variant="h4">Payment transactions</Typography><Typography color="text.secondary">Ingest, validate, price and charge a client transaction exactly once.</Typography></Box>{error&&<Alert severity="error">{error.message}</Alert>}
 <TextField select label="Customer" value={customerId} onChange={e=>setCustomerId(e.target.value)} sx={{maxWidth:520}}>{customers.data?.content.map(c=><MenuItem key={c.id} value={c.id}>{c.customerName} · {c.customerCode}</MenuItem>)}</TextField>
 {customerId&&<Stack direction={{xs:'column',md:'row'}} spacing={2}>{([['Total',summary.data?.total],['Completed',summary.data?.completed],['Rejected',summary.data?.rejected],['Pending reconciliation',summary.data?.pendingReconciliation],['Exceptions',summary.data?.reconciliationExceptions],['Total charges',summary.data?.totalCharges]] as const).map(([label,value])=><Card key={label} sx={{flex:1}}><CardContent><Typography color="text.secondary" variant="body2">{label}</Typography><Typography variant="h5">{value??'—'}</Typography></CardContent></Card>)}</Stack>}
 {customerId&&<><Card><CardContent><Box component="form" onSubmit={submit}><Typography variant="h6" mb={2}>Submit transaction</Typography><Stack spacing={2}><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField required fullWidth label="Client reference" value={form.clientReferenceId} onChange={e=>setForm(v=>({...v,clientReferenceId:e.target.value}))}/><TextField required fullWidth label="Product code" value={form.productCode} onChange={e=>setForm(v=>({...v,productCode:e.target.value.toUpperCase()}))}/><TextField required fullWidth label="Transaction type" value={form.transactionType} onChange={e=>setForm(v=>({...v,transactionType:e.target.value.toUpperCase()}))}/></Stack><Stack direction={{xs:'column',md:'row'}} spacing={2}><TextField required fullWidth type="number" inputProps={{min:.0001,step:.0001}} label="Amount" value={form.amount} onChange={e=>setForm(v=>({...v,amount:Number(e.target.value)}))}/><TextField required fullWidth label="Currency" value={form.currency} onChange={e=>setForm(v=>({...v,currency:e.target.value.toUpperCase()}))}/><TextField fullWidth label="Source account" value={form.sourceAccount} onChange={e=>setForm(v=>({...v,sourceAccount:e.target.value}))}/><TextField fullWidth label="Destination account" value={form.destinationAccount} onChange={e=>setForm(v=>({...v,destinationAccount:e.target.value}))}/></Stack><Button type="submit" variant="contained" disabled={ingest.isPending}>{ingest.isPending?'Processing…':'Submit transaction'}</Button></Stack></Box></CardContent></Card>
 <Card><CardContent><Typography variant="h6" mb={2}>Transaction history</Typography><Stack direction={{xs:'column',md:'row'}} spacing={1.5} mb={2}><TextField size="small" label="Reference" value={filters.reference} onChange={e=>setFilters(v=>({...v,reference:e.target.value}))}/><TextField size="small" label="Product" value={filters.product} onChange={e=>setFilters(v=>({...v,product:e.target.value.toUpperCase()}))}/><TextField size="small" select label="Status" value={filters.status} onChange={e=>setFilters(v=>({...v,status:e.target.value}))} sx={{minWidth:150}}><MenuItem value="">All</MenuItem>{['RECEIVED','VALIDATING','ACCEPTED','PROCESSING','COMPLETED','REJECTED','FAILED'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField size="small" type="date" label="From" InputLabelProps={{shrink:true}} value={filters.from} onChange={e=>setFilters(v=>({...v,from:e.target.value}))}/><TextField size="small" type="date" label="To" InputLabelProps={{shrink:true}} value={filters.to} onChange={e=>setFilters(v=>({...v,to:e.target.value}))}/><Button variant="outlined" component="label">Import CSV<input hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importBatch(e.target.files[0])}/></Button><Button variant="outlined" onClick={exportCsv}>Export CSV</Button></Stack>{batchResult&&<Alert severity="success" sx={{mb:2}}>{batchResult}</Alert>}<Box sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{['Reference','Product / type','Amount','Status','Charge','Reconciliation','Source','Created'].map(h=><TableCell key={h} sx={{fontWeight:800}}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{transactions.data?.map(t=><TableRow hover key={t.id} onClick={()=>setSelected(t)} sx={{cursor:'pointer'}}><TableCell>{t.clientReferenceId}<Typography display="block" variant="caption">{t.id}</Typography></TableCell><TableCell>{t.productCode} / {t.transactionType}</TableCell><TableCell>{t.currency} {t.amount}</TableCell><TableCell><Chip size="small" label={t.status} color={t.status==='COMPLETED'?'success':t.status==='REJECTED'?'error':'default'}/></TableCell><TableCell>{t.totalCharge==null?'—':`${t.currency} ${t.totalCharge}`}</TableCell><TableCell>{t.reconciliationStatus}</TableCell><TableCell>{t.ingestionSource}</TableCell><TableCell>{new Date(t.createdAt).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table></Box></CardContent></Card></>}
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>Transaction detail</DialogTitle><DialogContent>{selected&&<Stack spacing={2} mt={1}><Typography><b>Reference:</b> {selected.clientReferenceId}</Typography><Typography><b>Transaction ID:</b> {selected.id}</Typography><Typography><b>Kind / source:</b> {selected.transactionKind} / {selected.ingestionSource}</Typography><Typography><b>Route:</b> {selected.sourceAccount||'—'} → {selected.destinationAccount||'—'}</Typography><Typography><b>Pricing version:</b> {selected.pricingPlanVersionId||'—'}</Typography><Typography><b>Charge:</b> {selected.totalCharge==null?'—':`${selected.currency} ${selected.totalCharge} (base ${selected.baseFee} + tax ${selected.taxAmount}) · ${selected.chargeStatus}`}</Typography><Typography><b>Reconciliation:</b> {selected.reconciliationStatus} {selected.externalSettlementReference&&`· ${selected.externalSettlementReference}`}</Typography>{selected.failureReason&&<Alert severity="error">{selected.failureReason}</Alert>}<Typography variant="h6">Lifecycle</Typography>{selected.history.map((h,index)=><Box key={`${h.status}-${h.createdAt}`} sx={{pl:2,borderLeft:'3px solid #D9E2F2'}}><Typography fontWeight={700}>{index+1}. {h.status}</Typography><Typography variant="body2" color="text.secondary">{h.detail} · {new Date(h.createdAt).toLocaleString()}</Typography></Box>)}</Stack>}</DialogContent><DialogActions>{selected?.status==='COMPLETED'&&selected.transactionKind==='PAYMENT'&&<Button color="error" disabled={reverse.isPending} onClick={()=>reverse.mutate(selected)}>Reverse</Button>}{selected?.status==='COMPLETED'&&<><Button disabled={reconcile.isPending} onClick={()=>reconcile.mutate({t:selected,status:'EXCEPTION'})}>Exception</Button><Button disabled={reconcile.isPending} onClick={()=>reconcile.mutate({t:selected,status:'MATCHED'})}>Match</Button></>}<Button onClick={()=>setSelected(null)}>Close</Button></DialogActions></Dialog>
 </Stack>;
}
