package com.nimbusbill.customer.entity;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.UUID;
@Entity @Table(name="invoices") public class Invoice {
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @OneToOne(optional=false) @JoinColumn(name="billing_run_id",unique=true) private BillingRun billingRun; @ManyToOne(optional=false) @JoinColumn(name="customer_id") private Customer customer; @ManyToOne(optional=false) @JoinColumn(name="billing_account_id") private BillingAccount billingAccount;
 @Column(name="invoice_number",nullable=false,unique=true,length=40) private String invoiceNumber; @Column(nullable=false,length=20) private String status="DRAFT"; @Column(name="invoice_date",nullable=false) private LocalDate invoiceDate; @Column(name="due_date",nullable=false) private LocalDate dueDate; @Column(nullable=false,length=3) private String currency;
 @Column(nullable=false,precision=19,scale=4) private BigDecimal subtotal; @Column(name="tax_total",nullable=false,precision=19,scale=4) private BigDecimal taxTotal; @Column(name="adjustment_total",nullable=false,precision=19,scale=4) private BigDecimal adjustmentTotal=BigDecimal.ZERO; @Column(name="grand_total",nullable=false,precision=19,scale=4) private BigDecimal grandTotal;
 @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="submitted_at") private Instant submittedAt; @Column(name="approved_at") private Instant approvedAt; @Column(name="issued_at") private Instant issuedAt;
 @PrePersist void create(){createdAt=Instant.now();updatedAt=createdAt;} @PreUpdate void update(){updatedAt=Instant.now();}
 public UUID getId(){return id;} public BillingRun getBillingRun(){return billingRun;} public void setBillingRun(BillingRun v){billingRun=v;} public Customer getCustomer(){return customer;} public void setCustomer(Customer v){customer=v;} public BillingAccount getBillingAccount(){return billingAccount;} public void setBillingAccount(BillingAccount v){billingAccount=v;} public String getInvoiceNumber(){return invoiceNumber;} public void setInvoiceNumber(String v){invoiceNumber=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDate getInvoiceDate(){return invoiceDate;} public void setInvoiceDate(LocalDate v){invoiceDate=v;} public LocalDate getDueDate(){return dueDate;} public void setDueDate(LocalDate v){dueDate=v;} public String getCurrency(){return currency;} public void setCurrency(String v){currency=v;} public BigDecimal getSubtotal(){return subtotal;} public void setSubtotal(BigDecimal v){subtotal=v;} public BigDecimal getTaxTotal(){return taxTotal;} public void setTaxTotal(BigDecimal v){taxTotal=v;} public BigDecimal getAdjustmentTotal(){return adjustmentTotal;} public void setAdjustmentTotal(BigDecimal v){adjustmentTotal=v;} public BigDecimal getGrandTotal(){return grandTotal;} public void setGrandTotal(BigDecimal v){grandTotal=v;} public Instant getCreatedAt(){return createdAt;} public Instant getSubmittedAt(){return submittedAt;} public void setSubmittedAt(Instant v){submittedAt=v;} public Instant getApprovedAt(){return approvedAt;} public void setApprovedAt(Instant v){approvedAt=v;} public Instant getIssuedAt(){return issuedAt;} public void setIssuedAt(Instant v){issuedAt=v;}
}
