package com.nimbusbill.customer.entity;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.*; import java.util.UUID;
@Entity @Table(name="pricing_overrides") public class PricingOverride{
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @ManyToOne(optional=false) private Customer customer; @ManyToOne(optional=false) private PaymentProduct product;
 @Enumerated(EnumType.STRING) @Column(name="charge_type",nullable=false,length=20) private PricingUnit chargeType; @Column(name="fixed_fee",precision=19,scale=4) private BigDecimal fixedFee; @Column(name="percentage_rate",precision=12,scale=6) private BigDecimal percentageRate; @Column(name="minimum_fee",precision=19,scale=4) private BigDecimal minimumFee; @Column(name="maximum_fee",precision=19,scale=4) private BigDecimal maximumFee; @Column(name="tax_rate",nullable=false,precision=8,scale=4) private BigDecimal taxRate=BigDecimal.ZERO;
 @Column(name="effective_from",nullable=false) private LocalDate effectiveFrom; @Column(name="effective_to") private LocalDate effectiveTo; @Column(nullable=false) private boolean active=true; @Column(length=300) private String reason; @Column(name="created_by",nullable=false,length=150) private String createdBy; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Version private long version;
 @PrePersist void create(){Instant n=Instant.now();createdAt=n;updatedAt=n;} @PreUpdate void update(){updatedAt=Instant.now();}
 public UUID getId(){return id;}public Customer getCustomer(){return customer;}public void setCustomer(Customer v){customer=v;}public PaymentProduct getProduct(){return product;}public void setProduct(PaymentProduct v){product=v;}public PricingUnit getChargeType(){return chargeType;}public void setChargeType(PricingUnit v){chargeType=v;}public BigDecimal getFixedFee(){return fixedFee;}public void setFixedFee(BigDecimal v){fixedFee=v;}public BigDecimal getPercentageRate(){return percentageRate;}public void setPercentageRate(BigDecimal v){percentageRate=v;}public BigDecimal getMinimumFee(){return minimumFee;}public void setMinimumFee(BigDecimal v){minimumFee=v;}public BigDecimal getMaximumFee(){return maximumFee;}public void setMaximumFee(BigDecimal v){maximumFee=v;}public BigDecimal getTaxRate(){return taxRate;}public void setTaxRate(BigDecimal v){taxRate=v;}public LocalDate getEffectiveFrom(){return effectiveFrom;}public void setEffectiveFrom(LocalDate v){effectiveFrom=v;}public LocalDate getEffectiveTo(){return effectiveTo;}public void setEffectiveTo(LocalDate v){effectiveTo=v;}public boolean isActive(){return active;}public void setActive(boolean v){active=v;}public String getReason(){return reason;}public void setReason(String v){reason=v;}public String getCreatedBy(){return createdBy;}public void setCreatedBy(String v){createdBy=v;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
}
