package com.nimbusbill.customer.entity;
import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Entity @Table(name="transfer_transactions",uniqueConstraints=@UniqueConstraint(name="uq_transfer_client_reference",columnNames={"customer_id","client_reference_id"})) public class TransferTransaction{
 @Id @GeneratedValue(strategy=GenerationType.UUID) private UUID id; @Column(name="client_reference_id",nullable=false,length=100) private String clientReferenceId; @ManyToOne(optional=false) private Customer customer;
 @ManyToOne(optional=false) @JoinColumn(name="source_account_id") private TransferAccount sourceAccount; @ManyToOne(optional=false) @JoinColumn(name="destination_account_id") private TransferAccount destinationAccount; @ManyToOne(optional=false) @JoinColumn(name="source_bridge_account_id") private TransferAccount sourceBridgeAccount; @ManyToOne(optional=false) @JoinColumn(name="destination_bridge_account_id") private TransferAccount destinationBridgeAccount;
 @Column(name="product_code",nullable=false,length=30) private String productCode; @Column(nullable=false,precision=19,scale=4) private BigDecimal amount; @Column(nullable=false,length=3) private String currency;
 @Enumerated(EnumType.STRING) @Column(nullable=false,length=30) private TransferStatus status; @Column(name="current_step",nullable=false) private short currentStep; @Enumerated(EnumType.STRING) @Column(name="billing_status",nullable=false,length=20) private BillingStatus billingStatus;
 @ManyToOne @JoinColumn(name="pricing_plan_version_id") private PricingPlanVersion pricingPlanVersion; @Column(name="failure_code",length=80) private String failureCode; @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="completed_at") private Instant completedAt; @Version private long version;
 @OneToMany(mappedBy="transfer",cascade=CascadeType.ALL) @OrderBy("legSequence") private List<TransferLeg> legs=new ArrayList<>();
 @PrePersist void create(){createdAt=Instant.now();if(status==null)status=TransferStatus.RECEIVED;if(billingStatus==null)billingStatus=BillingStatus.NOT_BILLED;}
 public UUID getId(){return id;} public String getClientReferenceId(){return clientReferenceId;} public void setClientReferenceId(String v){clientReferenceId=v;} public Customer getCustomer(){return customer;} public void setCustomer(Customer v){customer=v;} public TransferAccount getSourceAccount(){return sourceAccount;} public void setSourceAccount(TransferAccount v){sourceAccount=v;} public TransferAccount getDestinationAccount(){return destinationAccount;} public void setDestinationAccount(TransferAccount v){destinationAccount=v;} public TransferAccount getSourceBridgeAccount(){return sourceBridgeAccount;} public void setSourceBridgeAccount(TransferAccount v){sourceBridgeAccount=v;} public TransferAccount getDestinationBridgeAccount(){return destinationBridgeAccount;} public void setDestinationBridgeAccount(TransferAccount v){destinationBridgeAccount=v;} public String getProductCode(){return productCode;} public void setProductCode(String v){productCode=v;} public BigDecimal getAmount(){return amount;} public void setAmount(BigDecimal v){amount=v;} public String getCurrency(){return currency;} public void setCurrency(String v){currency=v;} public TransferStatus getStatus(){return status;} public void setStatus(TransferStatus v){status=v;} public short getCurrentStep(){return currentStep;} public void setCurrentStep(short v){currentStep=v;} public BillingStatus getBillingStatus(){return billingStatus;} public void setBillingStatus(BillingStatus v){billingStatus=v;} public PricingPlanVersion getPricingPlanVersion(){return pricingPlanVersion;} public void setPricingPlanVersion(PricingPlanVersion v){pricingPlanVersion=v;} public String getFailureCode(){return failureCode;} public void setFailureCode(String v){failureCode=v;} public Instant getCreatedAt(){return createdAt;} public Instant getCompletedAt(){return completedAt;} public void setCompletedAt(Instant v){completedAt=v;} public List<TransferLeg> getLegs(){return legs;}
 public enum TransferStatus{RECEIVED,FUNDS_CHECKED,IN_PROGRESS,COMPLETED,FAILED,REVERSING,REVERSED} public enum BillingStatus{NOT_BILLED,BILLED,REVERSED}
}
