package com.nimbusbill.customer.controller;
import com.nimbusbill.customer.dto.*;import com.nimbusbill.customer.entity.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import tools.jackson.databind.ObjectMapper;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class Phase3PricingCoverageTest{
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;
 @Test void calculationsBoundsSlabsAndCurrency()throws Exception{ProductFixture pct=product("PCT",PricingUnit.PERCENTAGE),hyb=product("HYB",PricingUnit.HYBRID),slb=product("SLB",PricingUnit.SLAB);UUID pp=activate("PCT",new PricingRuleRequest(pct.id(),PricingUnit.PERCENTAGE,null,new BigDecimal("2"),new BigDecimal("5"),new BigDecimal("15"),BigDecimal.ZERO,1,List.of()));preview(pp,pct.code(),"100","INR").andExpect(jsonPath("$.baseFee").value(5.0));preview(pp,pct.code(),"1000","INR").andExpect(jsonPath("$.baseFee").value(15.0));UUID hp=activate("HYB",new PricingRuleRequest(hyb.id(),PricingUnit.HYBRID,new BigDecimal("3"),new BigDecimal("1"),null,null,BigDecimal.ZERO,1,List.of()));preview(hp,hyb.code(),"1000","INR").andExpect(jsonPath("$.baseFee").value(13.0));List<PricingSlabRequest> slabs=List.of(new PricingSlabRequest(BigDecimal.ZERO,new BigDecimal("100"),BigDecimal.ONE,null,1),new PricingSlabRequest(new BigDecimal("100.01"),null,new BigDecimal("2"),new BigDecimal("1"),2));UUID sp=activate("SLB",new PricingRuleRequest(slb.id(),PricingUnit.SLAB,null,null,null,null,BigDecimal.ZERO,1,slabs));preview(sp,slb.code(),"100","INR").andExpect(jsonPath("$.baseFee").value(1.0));preview(sp,slb.code(),"100.01","INR").andExpect(jsonPath("$.baseFee").value(3.0001));mvc.perform(post("/api/v1/pricing/preview").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(new PricingPreviewRequest(sp,slb.code(),new BigDecimal("100"),LocalDate.now(),"USD")))).andExpect(status().isConflict());}
 @Test void overlappingSlabsRejected()throws Exception{ProductFixture p=product("OVR",PricingUnit.SLAB);List<PricingSlabRequest> slabs=List.of(new PricingSlabRequest(BigDecimal.ZERO,new BigDecimal("100"),BigDecimal.ONE,null,1),new PricingSlabRequest(new BigDecimal("100"),null,BigDecimal.TEN,null,2));PricingPlanRequest r=new PricingPlanRequest(code("PLAN"),"Overlap",null,"INR",LocalDate.now(),null,List.of(new PricingRuleRequest(p.id(),PricingUnit.SLAB,null,null,null,null,BigDecimal.ZERO,1,slabs)));mvc.perform(post("/api/v1/pricing-plans").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(r))).andExpect(status().isBadRequest());}
 private ProductFixture product(String prefix,PricingUnit unit)throws Exception{String code=code(prefix);ProductRequest r=new ProductRequest(code,code,null,unit,null,null,true,ProductStatus.ACTIVE,LocalDate.now(),null,Set.of(code,"INTERNAL_TRANSFER"),Set.of("INR"));String body=mvc.perform(post("/api/v1/products").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(r))).andExpect(status().isCreated()).andExpect(jsonPath("$.currencies[0]").value("INR")).andReturn().getResponse().getContentAsString();return new ProductFixture(UUID.fromString(json.readTree(body).get("id").asText()),code);}
 private UUID activate(String prefix,PricingRuleRequest rule)throws Exception{PricingPlanRequest r=new PricingPlanRequest(code("PLAN_"+prefix),prefix+" Plan",null,"INR",LocalDate.now(),null,List.of(rule));String body=mvc.perform(post("/api/v1/pricing-plans").header("X-Actor","maker").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(r))).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();var root=json.readTree(body);String plan=root.get("id").asText(),version=root.get("versions").get(0).get("id").asText();mvc.perform(post("/api/v1/pricing-plans/{p}/versions/{v}/submit",plan,version).header("X-Actor","maker")).andExpect(status().isOk());mvc.perform(post("/api/v1/pricing-plans/{p}/versions/{v}/approve",plan,version).header("X-Actor","checker")).andExpect(status().isOk());mvc.perform(post("/api/v1/pricing-plans/{p}/versions/{v}/activate",plan,version).header("X-Actor","admin")).andExpect(status().isOk());return UUID.fromString(plan);}
 private ResultActions preview(UUID plan,String product,String amount,String currency)throws Exception{return mvc.perform(post("/api/v1/pricing/preview").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(new PricingPreviewRequest(plan,product,new BigDecimal(amount),LocalDate.now(),currency)))).andExpect(status().isOk());}private String code(String p){return(p+"_"+UUID.randomUUID().toString().substring(0,8)).toUpperCase();}private record ProductFixture(UUID id,String code){}
}
